name: 'Bundlewatch - PR'

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: pnpm run bootstrap
      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: pnpm run build:minify
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
