name: 'Tests and Coverage - master'

on:
  push:
    branches:
      - master

jobs:
  codecoverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: 'Setup'
        run: pnpm run bootstrap
      - name: 'Run tests'
        run: pnpm run test:coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./packages/react-isomorphic-data/coverage/coverage-final.json
          fail_ci_if_error: true #optional (default = false)
